quarkus:
  http:
    port: 8802
  hibernate-orm:
    sql-load-script: import.sql
    log:
      sql: true
    database:
      generation: drop-and-create
  datasource:
    db-kind: mysql
    username: root
    password: 123456
    jdbc:
      url: jdbc:mysql://localhost:3306/panache_db
